url: http://gongqingfeng.github.io
baseurl: ""

# Site Settings
title: Gong Qingfeng
description: "Gong Qingfeng Homepage"
keywords: "Gong, Qingfeng, Computer Science, Electrical Engineering"
collections:
 notes:
    name: Notes
    documentation: https://github.com/Shopify/liquid/wiki/Liquid-for-Designers
    output: true
markdown: kramdown
exclude: ["Rakefile", "LICENSE", "readme.markdown"]